# Site settings
title: Anthony V. Pileggi
email: anthony@ifixit.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about datas.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://anthonypileggi.github.io" # the base hostname & protocol for your site
twitter_username: anthonyvpileggi
github_username:  anthonypileggi
permalink: /:year/:month/:title.html

# Build settings
markdown: kramdown
